### ISSUE TITLE
 Manufacture name gets "cut off"

### ISSUE THREAD

**Issue by vincentcox-work** [sensepost/peanuts#1]
Is it possible to remove the character limit of Manufacture name? Now "Microsoft" gets saved as "Microsof".

**Comment by NoobieDog** [comment]
@vincentcox-ordina As you can see from the screenshot posted below, the cut off its 8 chars from the manuf file. I will look at other ways of getting the Manufacturer data to fully represented in the near future.

[![screenshot]1](https://cloud.githubusercontent.com/assets/6222279/26373626/251f8130-3ffa-11e7-8a60-b587bb28dca2.png)
