### ISSUE TITLE
[Feature request] Is it possible to get the signal strength?

### ISSUE THREAD

**Issue by vincentcox-work** [sensepost/peanuts#2]
If possible, it can be useful to have the signal strength of each client. This way it can be possible to have a sense of the distance the client is.

**Comment by NoobieDog** [comment]
Vincent, thanks for the requests,

For sure, im releasing a new version in next few days with some additional
features such as mapping options and the things you have requested too,
also we are working hard on work arounds for some of the MAC random
techniques.

Thank you for the interest.

Stu

**Comment by strasharo** [comment]
Yep, should be possible, was recently added to whoiswhere:

https://github.com/hkm/whoishere.py/pull/3

Although in the implementation there I found it to be driver specific, because at least for me it wasn't reporting any values on ath9k. Working fine on rtl8187 though.

**Comment by NoobieDog** [comment]
Ive added a simple RSSI feature and its now logged.

I will add a better version over the next week or so

Stu
